import { User } from '../../types/user';
import { DomainError } from '../errors/DomainError';
import { IUserRepository } from '../repositories/IUserRepository';
import { IPasswordHasher } from '../services';
import { Email, Password, Username } from '../value-objects';

interface RegisterUserInput {
  username: string;
  email: string;
  password: string;
}

/**
 * Use case for public user registration
 * Registers a new user without any roles (admin must assign roles later)
 */
export class RegisterUserUseCase {
  constructor(
    private readonly userRepository: IUserRepository,
    private readonly passwordHasher: IPasswordHasher
  ) {}

  async execute(input: RegisterUserInput): Promise<User> {
    // Validate input with Value Objects
    const username = Username.create(input.username);
    const email = Email.create(input.email);
    const password = Password.create(input.password);

    // Check if username already exists
    const existingUsername = await this.userRepository.findByUsername(username.getValue());
    if (existingUsername) {
      throw new DomainError('Username already exists', 'DUPLICATE_USERNAME');
    }

    // Check if email already exists
    const existingEmail = await this.userRepository.findByEmail(email.getValue());
    if (existingEmail) {
      throw new DomainError('Email already exists', 'DUPLICATE_EMAIL');
    }

    // Hash password
    const passwordHash = await this.passwordHasher.hash(password.getValue());

    // Create user entity (id will be auto-generated by database)
    const newUser: User = {
      id: '', // Will be set by database SERIAL
      username: username.getValue(),
      email: email.getValue(),
      passwordHash,
      createdAt: new Date().toISOString()
    };

    // Save user
    const createdUser = await this.userRepository.create(newUser);

    // Return user without password hash
    return {
      id: createdUser.id,
      username: createdUser.username,
      email: createdUser.email,
      passwordHash: undefined as any,
      createdAt: createdUser.createdAt
    };
  }
}
